"""Export logic for building X-Plane scenery packages."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from zipfile import ZipFile

from hems_generator.scene import Scene
from hems_generator.utils import write_text


@dataclass(frozen=True)
class SceneryPackage:
    faa_id: str
    name: str
    root_dir: Path

    @property
    def package_name(self) -> str:
        return f"HOSP_{self.faa_id}_{self.name}"

    @property
    def package_dir(self) -> Path:
        return self.root_dir / self.package_name

    @property
    def scenery_path(self) -> Path:
        return self.package_dir / "Custom Scenery" / self.package_name

    def build_skeleton(self) -> None:
        scenery_root = self.scenery_path
        write_text(
            scenery_root / "library.txt",
            "# Placeholder library file for hospital scenery package.\n",
        )
        write_text(
            scenery_root / "Earth nav data" / "placeholder.dsf",
            "# DSF placeholder generated by HEMS generator.\n",
        )
        write_text(
            scenery_root / "objects" / "hospital_0.obj",
            "# OBJ placeholder. Replace with generated mesh.\n",
        )
        write_text(
            scenery_root / "objects" / "README.txt",
            "Procedural objects will be written here during pipeline execution.\n",
        )
        write_text(
            scenery_root / "textures" / "README.txt",
            "Procedural textures will be written here during pipeline execution.\n",
        )
        write_text(
            scenery_root / "polygons" / "README.txt",
            "Draped polygons (.pol) will be written here during pipeline execution.\n",
        )
        write_text(
            scenery_root / "lines" / "README.txt",
            "Line definitions (.lin) will be written here during pipeline execution.\n",
        )

    def write_scene(self, scene: Scene) -> None:
        write_text(
            self.scenery_path / "scene.json",
            scene.to_json(),
        )

    def zip_to(self, target_zip: Path) -> None:
        target_zip.parent.mkdir(parents=True, exist_ok=True)
        base_dir = self.package_dir
        with ZipFile(target_zip, "w") as archive:
            for path in base_dir.rglob("*"):
                archive.write(path, path.relative_to(self.root_dir))
